node('masterLin'){
    
    wrap([$class: 'TimestamperBuildWrapper']){
        wrap([$class: 'AnsiColorBuildWrapper']){
            wrap([$class: 'BuildUser']) {
                starter_email = env.BUILD_USER_EMAIL 
                starter_name = env.BUILD_USER
                starter_name_id = env.BUILD_USER_ID
            }
            currentBuild.result = 'SUCCESS'       

            deleteDir()

            stage('Clone git'){
                git branch: 'master',
                url: 'https://github.com/flameraven/test_pipeline.git'
            }

            stage('Build docker image'){
                app = docker.build('app_v1')
            }

            stage('Push image'){
                docker.withRegistry('https://localhost:8083', 'docker_registry') {
                    app.push("${env.BUILD_NUMBER}")
                    app.push("latest")
                }         
            }            
        }
    }
}